#cloud-config

# Perform a yum package upgrade on the machine
package_upgrade: true

# Install the google-authenticator package which provides the "pam_google_authenticator.so" module
packages:
 - google-authenticator

# Transfer Google Authenticator configuration into ec2_user with correct permissions, owner, etc
write_files:
  - path: /home/ec2-user/.google_authenticator
      permissions: '0400'
      owner: ec2-user:ec2-user
      encoding: b64
      content: SFBZQldNS0FFR1VPUUQ1RgoiIFJBVEVfTElNSVQgMyAzMAoiIERJU0FMTE9XX1JFVVNFCiIgVE9U
               UF9BVVRICjg3ODE5NzkzCjc5MjI4NjQ2CjE4OTEyNzA2CjUxMDIxMzUwCjIzNzg5MjI0Cg==
# Execute the following commands
runcmd:
  - echo "PAM Google Authenticator Changes"  

# Setup PAM to require Google Authenticator Token
# Add "nullok" option after "pam_google_authenticator.so" if you want to accept access for users via just SSH key i.e. no MFA
  - echo "auth required pam_google_authenticator.so" >> /etc/pam.d/sshd
# Prevent PAM authentication via password
  - sed -e '/auth       substack     password-auth/ s/^#*/#/' -i /etc/pam.d/sshd
  - echo "SSHD Google Authenticator Changes"
# Set ChallengeResponseAuthentication to Yes
  - sed -e '/ChallengeResponseAuthentication no/ s/^#*/#/' -i /etc/ssh/sshd_config
  - sed -e '/ChallengeResponseAuthentication yes/ s/^#*//' -i /etc/ssh/sshd_config
# Set AuthenticationMethods
  - echo -e "\nAuthenticationMethods publickey,keyboard-interactive" >>  /etc/ssh/sshd_config
# Restart sshd
  - sudo /etc/init.d/sshd reload
